import json

# Load the countriesInfo.json file
file_path = r"C:\Users\henry\Documents\GitHub\MapApp\MapApp\src\countriesInfo.json"
with open(file_path, "r") as file:
    countries_info = json.load(file)

# Poverty data provided by the user
poverty_data = [
    {"country": "Somalia", "povertyPercentage": 54.4, "year": 2022},
    {"country": "Malawi", "povertyPercentage": 50.7, "year": 2019},
    {"country": "South Sudan", "povertyPercentage": 82.3, "year": 2016},
    {"country": "Niger", "povertyPercentage": 40.8, "year": 2018},
    {"country": "Nigeria", "povertyPercentage": 40.1, "year": 2018},
    {"country": "Rwanda", "povertyPercentage": 38.2, "year": 2016},
    {"country": "Tanzania", "povertyPercentage": 26.4, "year": 2018},
    {"country": "Uganda", "povertyPercentage": 20.3, "year": 2019},
    {"country": "Liberia", "povertyPercentage": 50.9, "year": 2016},
    {"country": "Guinea", "povertyPercentage": 43.7, "year": 2018},
    {"country": "Sierra Leone", "povertyPercentage": 56.8, "year": 2018},
    {"country": "Chad", "povertyPercentage": 42.3, "year": 2018},
    {"country": "Guinea Bissau", "povertyPercentage": 47.7, "year": 2018},
    {"country": "Bangladesh", "povertyPercentage": 18.7, "year": 2022},
    {"country": "Pakistan", "povertyPercentage": 21.9, "year": 2018},
    {"country": "Benin", "povertyPercentage": 38.5, "year": 2018},
    {"country": "India", "povertyPercentage": 21.9, "year": 2011},
    {"country": "Togo", "povertyPercentage": 45.5, "year": 2018},
    {"country": "Mali", "povertyPercentage": 44.6, "year": 2021},
    {"country": "Zimbabwe", "povertyPercentage": 38.3, "year": 2019},
    {"country": "Vanuatu", "povertyPercentage": 15.9, "year": 2019},
    {"country": "Lesotho", "povertyPercentage": 49.7, "year": 2017},
    {"country": "Ghana", "povertyPercentage": 23.4, "year": 2016},
    {"country": "Sao Tome and Principe", "povertyPercentage": 55.5, "year": 2018},
    {"country": "Djibouti", "povertyPercentage": 21.1, "year": 2017},
    {"country": "Kiribati", "povertyPercentage": 21.9, "year": 2019},
    {"country": "Angola", "povertyPercentage": 32.3, "year": 2018},
    {"country": "Burkina Faso", "povertyPercentage": 59.8, "year": None},
    {"country": "Ivory Coast", "povertyPercentage": 39.5, "year": 2018},
    {"country": "Kyrgyzstan", "povertyPercentage": 33.3, "year": 2021},
    {"country": "Senegal", "povertyPercentage": 46.7, "year": 2011},
    {"country": "Myanmar", "povertyPercentage": 24.8, "year": 2017},
    {"country": "Laos", "povertyPercentage": 18.3, "year": 2018},
    {"country": "Eswatini", "povertyPercentage": 58.9, "year": 2016},
    {"country": "Armenia", "povertyPercentage": 26.5, "year": 2021},
    {"country": "Philippines", "povertyPercentage": 18.1, "year": 2021},
    {"country": "Georgia", "povertyPercentage": 15.6, "year": 2022},
    {"country": "Indonesia", "povertyPercentage": 9.5, "year": 2022},
    {"country": "Fiji", "povertyPercentage": 24.1, "year": 2019},
    {"country": "Sri Lanka", "povertyPercentage": 14.3, "year": 2019},
    {"country": "Honduras", "povertyPercentage": 48.0, "year": 2019},
    {"country": "Mongolia", "povertyPercentage": 27.8, "year": 2020},
    {"country": "Peru", "povertyPercentage": 27.5, "year": 2022},
    {"country": "Colombia", "povertyPercentage": 39.3, "year": 2021},
    {"country": "Bhutan", "povertyPercentage": 12.4, "year": 2022},
    {"country": "Marshall Islands", "povertyPercentage": 7.2, "year": 2019},
    {"country": "Ecuador", "povertyPercentage": 25.2, "year": 2022},
    {"country": "Mexico", "povertyPercentage": 36.3, "year": 2022},
    {"country": "Gabon", "povertyPercentage": 33.4, "year": 2017},
    {"country": "Kazakhstan", "povertyPercentage": 5.2, "year": 2022},
    {"country": "Vietnam", "povertyPercentage": 4.8, "year": 2020},
    {"country": "Brazil", "povertyPercentage": None, "year": None},
    {"country": "South Korea", "povertyPercentage": None, "year": None},
    {"country": "United States", "povertyPercentage": 18.0, "year": None},
    {"country": "Palestine", "povertyPercentage": None, "year": None},
    {"country": "Saint Lucia", "povertyPercentage": 25.0, "year": 2016},
    {"country": "Paraguay", "povertyPercentage": 24.7, "year": 2022},
    {"country": "North Macedonia", "povertyPercentage": 21.8, "year": 2019},
    {"country": "Costa Rica", "povertyPercentage": 25.5, "year": 2022},
    {"country": "Thailand", "povertyPercentage": 6.3, "year": 2021},
    {"country": "Mauritius", "povertyPercentage": 10.3, "year": 2017},
    {"country": "Bolivia", "povertyPercentage": 36.4, "year": 2021},
    {"country": "Albania", "povertyPercentage": 22.0, "year": 2020},
    {"country": "Montenegro", "povertyPercentage": 21.2, "year": 2020},
    {"country": "Serbia", "povertyPercentage": 21.2, "year": 2020},
    {"country": "Ukraine", "povertyPercentage": 1.6, "year": 2020},
    {"country": "Turkey", "povertyPercentage": 14.4, "year": 2020},
    {"country": "Chile", "povertyPercentage": 10.8, "year": 2020},
    {"country": "Panama", "povertyPercentage": 21.5, "year": 2019},
    {"country": "Romania", "povertyPercentage": 21.2, "year": 2021},
    {"country": "Uruguay", "povertyPercentage": 9.9, "year": 2022},
    {"country": "Maldives", "povertyPercentage": 5.4, "year": 2019},
    {"country": "Russia", "povertyPercentage": 12.1, "year": 2020},
    {"country": "Seychelles", "povertyPercentage": 25.3, "year": 2018},
    {"country": "Bulgaria", "povertyPercentage": 22.9, "year": 2021},
    {"country": "Poland", "povertyPercentage": 11.8, "year": 2022},
    {"country": "Greece", "povertyPercentage": 18.8, "year": 2021},
    {"country": "Israel", "povertyPercentage": 16.9, "year": None},
    {"country": "Latvia", "povertyPercentage": 22.5, "year": 2021},
    {"country": "Croatia", "povertyPercentage": 18.0, "year": 2018},
    {"country": "Slovakia", "povertyPercentage": 13.7, "year": 2021},
    {"country": "Italy", "povertyPercentage": 20.1, "year": 2021},
    {"country": "Spain", "povertyPercentage": 20.4, "year": 2021},
    {"country": "Portugal", "povertyPercentage": 16.4, "year": 2021},
    {"country": "Lithuania", "povertyPercentage": 20.9, "year": 2021},
    {"country": "Estonia", "povertyPercentage": 22.8, "year": 2021},
    {"country": "United Kingdom", "povertyPercentage": 18.6, "year": 2017},
    {"country": "Australia", "povertyPercentage": 12.6, "year": None},
    {"country": "Sweden", "povertyPercentage": 16.0, "year": 2021},
    {"country": "Canada", "povertyPercentage": 10.5, "year": None},
    {"country": "Austria", "povertyPercentage": 14.8, "year": 2021},
    {"country": "Malta", "povertyPercentage": 16.7, "year": 2021},
    {"country": "Czech Republic", "povertyPercentage": 10.2, "year": 2021},
    {"country": "Netherlands", "povertyPercentage": 14.5, "year": 2021},
    {"country": "Germany", "povertyPercentage": 14.7, "year": 2021},
    {"country": "Norway", "povertyPercentage": 12.7, "year": 2019},
    {"country": "Cyprus", "povertyPercentage": 13.9, "year": 2021},
    {"country": "Denmark", "povertyPercentage": 12.4, "year": 2021},
    {"country": "Switzerland", "povertyPercentage": 14.7, "year": 2020},
    {"country": "Slovenia", "povertyPercentage": 12.1, "year": 2021},
    {"country": "Luxembourg", "povertyPercentage": 17.4, "year": 2021},
    {"country": "France", "povertyPercentage": 15.6, "year": 2021},
    {"country": "Finland", "povertyPercentage": 12.7, "year": 2021},
    {"country": "Iceland", "povertyPercentage": 8.8, "year": 2017},
    {"country": "Ireland", "povertyPercentage": 14.0, "year": 2021},
    {"country": "Ethiopia", "povertyPercentage": 23.5, "year": 2015},
    {"country": "Egypt", "povertyPercentage": 29.7, "year": 2019},
    {"country": "DR Congo", "povertyPercentage": 63.9, "year": 2012},
    {"country": "South Africa", "povertyPercentage": 55.5, "year": 2014},
    {"country": "Kenya", "povertyPercentage": 36.1, "year": 2015},
    {"country": "Sudan", "povertyPercentage": 46.5, "year": 2009},
    {"country": "Algeria", "povertyPercentage": 5.5, "year": 2011},
    {"country": "Iraq", "povertyPercentage": 18.9, "year": 2012},
    {"country": "Argentina", "povertyPercentage": 39.2, "year": 2022},
    {"country": "Afghanistan", "povertyPercentage": 54.5, "year": 2016},
    {"country": "Yemen", "povertyPercentage": 48.6, "year": 2014},
    {"country": "Morocco", "povertyPercentage": 4.8, "year": 2013},
    {"country": "Uzbekistan", "povertyPercentage": 14.1, "year": 2013},
    {"country": "Malaysia", "povertyPercentage": 6.2, "year": 2021},
    {"country": "Mozambique", "povertyPercentage": 46.1, "year": 2014},
    {"country": "Madagascar", "povertyPercentage": 70.7, "year": 2012},
    {"country": "Nepal", "povertyPercentage": 25.2, "year": 2010},
    {"country": "Cameroon", "povertyPercentage": 37.5, "year": 2014},
    {"country": "Venezuela", "povertyPercentage": 33.1, "year": 2015},
    {"country": "Syria", "povertyPercentage": 35.2, "year": 2007},
    {"country": "Zambia", "povertyPercentage": 54.4, "year": 2015},
    {"country": "Guatemala", "povertyPercentage": 59.3, "year": 2014},
    {"country": "Cambodia", "povertyPercentage": 17.7, "year": 2012},
    {"country": "Burundi", "povertyPercentage": 64.9, "year": 2013},
    {"country": "Tunisia", "povertyPercentage": 16.6, "year": 2021},
    {"country": "Haiti", "povertyPercentage": 58.5, "year": 2012},
    {"country": "Belgium", "povertyPercentage": 13.2, "year": 2021},
    {"country": "Jordan", "povertyPercentage": 15.7, "year": 2018},
    {"country": "Tajikistan", "povertyPercentage": 22.5, "year": 2022},
    {"country": "Papua New Guinea", "povertyPercentage": 39.9, "year": 2009},
    {"country": "Azerbaijan", "povertyPercentage": 6.0, "year": 2012},
    {"country": "Hungary", "povertyPercentage": 12.1, "year": 2021},
    {"country": "Belarus", "povertyPercentage": 4.8, "year": 2020},
    {"country": "Nicaragua", "povertyPercentage": 24.9, "year": 2016},
    {"country": "El Salvador", "povertyPercentage": 26.6, "year": 2022},
    {"country": "Republic of the Congo", "povertyPercentage": 40.9, "year": 2011},
    {"country": "Lebanon", "povertyPercentage": 27.4, "year": 2011},
    {"country": "Central African Republic", "povertyPercentage": 68.8, "year": 2021},
    {"country": "Mauritania", "povertyPercentage": 31.8, "year": 2019},
    {"country": "Bosnia and Herzegovina", "povertyPercentage": 16.9, "year": 2015},
    {"country": "Namibia", "povertyPercentage": 17.4, "year": 2015},
    {"country": "Jamaica", "povertyPercentage": 19.9, "year": 2012},
    {"country": "Gambia", "povertyPercentage": 53.4, "year": 2020},
    {"country": "Botswana", "povertyPercentage": 16.1, "year": 2015},
    {"country": "Equatorial Guinea", "povertyPercentage": 76.8, "year": 2006},
    {"country": "Timor Leste", "povertyPercentage": 41.8, "year": 2014},
    {"country": "Comoros", "povertyPercentage": 42.4, "year": 2013},
    {"country": "Solomon Islands", "povertyPercentage": 12.7, "year": 2020},
    {"country": "Cape Verde", "povertyPercentage": 35.2, "year": 2015},
    {"country": "Samoa", "povertyPercentage": 21.9, "year": 2018},
    {"country": "Micronesia", "povertyPercentage": 41.2, "year": 2013},
    {"country": "Tonga", "povertyPercentage": 22.5, "year": 2009},
    {"country": "Palau", "povertyPercentage": 24.9, "year": 2006},
    {"country": "Tuvalu", "povertyPercentage": 26.3, "year": 2010}
]


# Update the countriesInfo.json with the new data
for data in poverty_data:
    country_name = data["country"].lower()
    poverty_percentage = data.get("povertyPercentage", 0.0)
    year = data.get("year", "Unknown")
    
    # Check if country exists in countriesInfo.json
    if country_name in countries_info:
        countries_info[country_name]["povertyPercentage"] = poverty_percentage
        countries_info[country_name]["year"] = year
    else:
        # Optionally, add new country if it doesn't exist
        countries_info[country_name] = {
            "info": "No additional info available.",
            "povertyPercentage": poverty_percentage,
            "year": year
        }

# Save the updated JSON back to a file
updated_file_path = r"C:\Users\henry\Documents\GitHub\MapApp\MapApp\src\countries_updated.json"
with open(updated_file_path, "w") as file:
    json.dump(countries_info, file, indent=4)

updated_file_path
